export const FETCH_QUIZES_START = "FETCH_QUIZES_START"
export const FETCH_QUIZES_SUCCES = "FETCH_QUIZES_SUCCES"
export const FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR"
export const FETCH_QUIZ_SUCCES = "FETCH_QUIZ_SUCCES"

export const QUIZ_SET_STATE = "QUIZ_SET_STATE"
export const QUIZ_NEXT_QUESTION = "QUIZ_NEXT_QUESTION"
export const QUIZ_FINISH = "QUIZ_FINISH"
export const RESTART_QUIZ = "RESTART_QUIZ"

export const CREATE_QUIZ_QUESTION = "CREATE_QUIZ_QUESTION"
export const RESET_QUIZ_CREATION = "RESET_QUIZ_CREATION"
export const FINISH_CREATE_QUIZ = "FINISH_CREATE_QUIZ"

export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_LOGOUT = "AUTH_LOGOUT"